on:
  push:
    branches:
      - build/android
env:
  TELEGRAM_TO: 257481278

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: yarn

      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v7
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: 📦 Install dependencies
        run: yarn install

      - name: Cancel previous EAS builds
        uses: darcien/cancel-expo-eas-builds-action@v1

      - name: 🚀 Build app
        run: eas build --platform android --non-interactive

      - name: Notify on telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ env.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Build workflow complete (android)
            Status: ${{ github.action_status }}
            Url: https://expo.dev/accounts/brew4k/projects/SunNUS/builds
